### ISSUE TITLE
Request Whitelist feature and custom connect wallet

### ISSUE THREAD

**Issue by IhsotasTon** [internet-identity-labs/identitykit#187]
Hi team, the process of integrating IdentityKit went smoothly.But we encountered the following two issues.

1. when integrating IdentityKit with Plug Wallet, I am unable to request the whitelist from Plug Wallet. This is due to Yuku using a large number of query and execution methods, which causes lots of pop up
![截屏2024-10-12 19 27 55](https://github.com/user-attachments/assets/8bf8fd12-2d98-4bc9-af59-e9adc2f4dc08)

2. I hope to manually select the wallet connection myself. I checked the source code, and it seems that I can only manually choose when I set the “signerId” in localStorage.

**Comment by dostro** [comment]
Hello there!

Re #1: As discussed off Github - you were using `authType = IdentityKitAuthType.Accounts` when it should be `authType = IdentityKitAuthType.Delegation`

Re #2: We're adding that ability in the next few days

I'll close this ticket but please feel free to open a new ticket requesting manual connection to specific wallets if you'd like!
